pipeline {
    agent {
        node {
            label 'Agent-1'
        }
    }

    environment { 
        Course = 'Jenkins'
    }

    options {
        timeout(time: 60, unit: 'MINUTES') 
        disableConcurrentBuilds()
        ansiColor('xterm')
    }

    stages {

        stage('Init') {
            steps {
                script {
                    withAWS(region:'us-east-1',credentials:'aws-creds') {
                        sh """
                        cd 10-sg
                        terraform init
                        """
                    }
                } 
            }
        }

        stage('Plan') {
            steps {
                script {
                    withAWS(region:'us-east-1',credentials:'aws-creds') {
                        sh """
                        cd 10-sg
                        terraform plan
                        """
                    }
                }
            }
        }

        stage('Apply') {
            steps {
                script {
                    withAWS(region:'us-east-1',credentials:'aws-creds') {
                        sh """
                        cd 10-sg
                        terraform apply -auto-approve
                        """
                    }
                }  
            }
        }

        stage('Parallel Stage') {
            parallel {
                stage('Bastion') {
                    steps {
                        script {
                            echo "Bastion Triggering downstream job: 20-bastion"
                            build job: '20-bastion',
                                wait: false,
                                propagate: false
                        }
                    }
                }
                stage('SG Rules') {
                    steps {
                        script {
                            echo "SG Rules Triggering downstream job: 30-sg-rules"
                            build job: '30-sg-rules',
                                wait: false,
                                propagate: false
                        }
                    }
                }
                stage('ECR') {
                    steps {
                        script {
                            echo "ECR Triggering downstream job: 40-ecr"
                            build job: '40-ecr',
                                wait: false,
                                propagate: false
                        }
                    }
                }
                stage('ACM') {
                    steps {
                        script {
                            echo "ACM Triggering downstream job: 70-acm"
                            build job: '70-acm',
                                wait: true,
                                propagate: false
                        }
                    }
                }
                stage('EKS') {
                    steps {
                        script {
                            echo "EKS Triggering downstream job: 90-eks"
                            build job: '90-eks',
                                wait: false,
                                propagate: false
                        }
                    }
                }

            }
        }

        stage('Ingress ALB') {
            steps {
                script {
                    echo "Ingress ALB Triggering downstream job: 80-ingress-alb"
                    build job: '80-ingress-alb',
                        wait: false,
                        propagate: false
                }
            }
        }


    }

    post { 
        always { 
            echo 'I will always say Hello again!'
            cleanWs()
        }
        success {
            echo 'I will run if success'
        }
        failure {
            echo 'I will not run if failure'
        }
        aborted {
            echo 'Pipeline is aborted'
        }
    }
}